name: e2e test
on: [push, pull_request]

jobs:
  e2e:
    name: e2e test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
  
      - name: run e2e
        run: |
          make e2e
